@echo off
echo Stopping containers...
docker-compose down

echo Removing volumes...
docker volume rm odoo-sf_odoo-data
docker volume rm odoo-sf_db-data

echo Rebuilding and starting containers...
docker-compose up -d --build

echo Done! Waiting for Odoo to start...
