{
    "name": "ORM Managment",
    "version": "16.0.1.0.0",
    "category": "Inventory",
    "summary": "Add custom button to fetch data from API and store in database",
    "author": "AIT solutions",
    "depends": ["base", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "views/api_product_tree_view.xml",
        "views/api_product_kanban_view.xml",
        "views/api_product_form_view.xml",
        "views/api_product_search_view.xml",
        "views/api_product_actions.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": True,
    "license": "LGPL-3",
}
